project_id = "nejiumsrxffxotcwtghi"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.ai-assist]
verify_jwt = false

[functions.master-login]
verify_jwt = false
